# kalamine keyboard layout descriptor
name = "El-Qwerty"                             # full layout name, displayed in the keyboard settings
name8 = "Elqwerty"                             # short Windows filename: no spaces, no special chars
locale = "fr"                                  # locale/language id
variant = "elqwerty"                           # layout variant id
author = "ElTurpin"                            # author name
description = "ElQwerty"
url = "https://OneDeadKey.github.com/kalamine"
version = "0.2.0"
geometry = "ISO"

base = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│ ~   │ !   │ @   │ #   │ $ ¤ │ %   │ ^   │ &   │ *   │ (   │ )   │ _   │ + ± ┃          ┃
│ `   │ 1 ¡ │ 2   │ 3   │ 4 € │ 5 ‰ │ 6   │ 7   │ 8   │ 9   │ 0 ° │ - — │ = ≠ ┃ ⌫        ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃ Q   │ W   │ E   │ R   │ T   ┃ Y   │ U   │ I   │ O   │ P   ┃ { “ ┆ } ” ┃       ┃
┃ ↹      ┃   æ │   é │   è │   ë │     ┃   ü │   ù │   ï │   œ │   ö ┃ [ « ┆ ] » ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃ A   │ S   │ D   │ F   │ G   ┃ H   │ J   │ K   │ L   │**   ┃ "   ┆ |   ┃      ┃
┃ ⇬       ┃   à │   ä │   ê │   - │     ┃   ŷ │   û │   î │   ô │     ┃ ' ` ┆ \   ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃     │ Z   │ X   │ C   │ V   │ B   ┃ N   │ M   │ ;   │ :   │ ? § ┃               ┃
┃ ⇧    ┃     │   â │   × │   ç │   _ │     ┃   ñ │   µ │ , … │ . · │ / ¿ ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''

altgr = '''
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┲━━━━━━━━━━┓
│     │   ¹ │   ² │   ³ │   ⁴ │   ⁵ │   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ │  *´ │     ┃          ┃
│     │   ₁ │   ₂ │   ₃ │   ₄ │   ₅ │   ₆ │   ₇ │   ₈ │   ₉ │   ₀ │  *` │  *~ ┃ ⌫        ┃
┢━━━━━┷━━┱──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┺━━┳━━━━━━━┫
┃        ┃     │   ≤ │   ≥ │  *¤ │   ‰ │     │     │     │     │     │     │  *¨ ┃       ┃
┃ ↹      ┃   @ │   < │   > │   $ │   % │   ^ │   & │     │   ` │   ' │     │  *^ ┃       ┃
┣━━━━━━━━┻┱────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┴┬────┺┓  ⏎   ┃
┃         ┃     │   ⁽ │   ⁾ │     │   ≠ │     │   ± │     │   ÷ │   × │     │     ┃      ┃
┃ ⇬       ┃   { │   ( │   ) │   } │   = │   \ │   + │   - │   / │   * |   " │  *µ ┃      ┃
┣━━━━━━┳━━┹──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┬──┴──┲━━┷━━━━━┻━━━━━━┫
┃      ┃     │     │     │     │     │   ≃ │   ¦ │   ¬ │     │     │     ┃               ┃
┃ ⇧    ┃     │   ~ │   [ │   ] │   _ │   # │   | │   ! │   ; │   : │   ? ┃ ⇧             ┃
┣━━━━━━┻┳━━━━┷━━┳━━┷━━━━┱┴─────┴─────┴─────┴─────┴─────┴─┲━━━┷━━━┳━┷━━━━━╋━━━━━━━┳━━━━━━━┫
┃       ┃       ┃       ┃                                ┃       ┃       ┃       ┃       ┃
┃ Ctrl  ┃ super ┃ Alt   ┃ ␣                              ┃ AltGr ┃ super ┃ menu  ┃ Ctrl  ┃
┗━━━━━━━┻━━━━━━━┻━━━━━━━┹────────────────────────────────┺━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━┛
'''

[spacebar]
shift = "\u0020"       # SPACE
altgr = "\u0020"       # SPACE
altgr_shift = "\u0020" # SPACE
1dk = "\u00a0"         # NO-BREAK SPACE
1dk_shift = "\u00a0"   # NO-BREAK SPACE

# `<LSGT>` key is blank because it will be use as a second AltGr key
